= Лабораторная работа №2 

== Исходное задание

- Создать проект
- Создать глобальную переменную типа `unsigned short` и присвоить ей значение 65535
- В функции main прибавить к данной переменной 1 - описать что получилось и почему.
- Поменять тип переменной на `signed short` и присвоить ей значение 32767
- В функции main прибавить к данной переменной 1 - описать что получилось и почему.
- Не меняя тип переменной взять адрес переменной (оператор &) - вывести адрес переменной в 
терминал
- Не меняя переменной, явно преобразовать адрес переменной к типу указатель на `short`, 
используя `reinterpret_cast` и присвоить локальной переменной типа `short*`. 

Должно получиться что-то типа этого:
```
short* ptr = reinterpret_cast<short*>(&myVar) ;
```
- Вывести в терминал значение указателя - пояснить что это за значение
- Разыменовать указатель и вывести в терминал значение лежащее по адресу, указанному в указателе.
- Сделать явное преобразование этого указателя к типу указателя на `int` `(int*)`
- (Разыменовать указатель из предыдущего пункта типа `int*`). Вывести значение лежащее по 
адресу указателя типа `int*` из предыдущего пункта. Объяснить полученный результат
- Заменить тип переменной с `unsigned short` на `short` и присвоить ей значение 65535
- В функции `main` вывести значение переменной, посмотреть её значение и объяснить это.
- Не меняя переменную в функции main сделать явное преобразование типа к `short`
```
std::cout << static_cast<short>(myVar) << std::endl ;
```
- объяснить полученный результат
- Создать переменную типа float и присвоить ей значение `40'000'000'000F`;
- Прибавить к этому значению 1.0f -  вывести значение в окно Watch - объяснить полученный 
результат
- Заменить тип переменной `float` на `double`
- Прибавить к этому значению `1.0f` - вывести в окно Watch - объяснить полученный результат. 

== Результат выполнения 

=== Создание проекта

Создание проекта осуществляется следующим образом: 
1. Зайдем во вкладку Project верхнего меню и нажмем на опцию Create New Project

2. Создадим проект на С++ с файлом main.cpp

3. Добавим созданный проект в существующее пространство Workspace 

== Работа с глабальными переменными

Создадим глобальную переменную типа `unsigned short` и присвоим ей значение 65535. После чего 
в функции main прибавим к данной переменной 1. 

Для этого напишем в файле main.cpp следующий код: 
```
#include <iostream>

short unsigned int myVar = 65535; 

int main()
{
  myVar++; 
  std::cout << "myVar = " << myVar << std::endl; 
  
  return 0;
}
```
Если запустить эту программу, то можно обнаружить, что переменная myVar стала равна 0. 

Так получилось из-за того, что произошло переполнение. 

Затем поменяем тип переменной на `signed short` и присвоить ей значение 32767 и в функции 
main прибавить к данной переменной 1. 

Изменим код следующим образом: 
```
#include <iostream>

signed short int myVar = 32767; 

int main()
{
  myVar++; 
  std::cout << "myVar = " << myVar << std::endl; 
  
  return 0;
}

```
Запустим программу и увидим, что значение переменной myVarстало равно -32768. 

В данном случае переполнения не произошло. 

== Работа с указателями на переменную 

Не меняя тип переменной, возьмем адрес переменной (оператор &) и выведем этот адрес в терминал. 

Для этого изменим код следующим образом: 
```
#include <iostream>

using tMyVar = short unsigned int; 
tMyVar myVar = 32767; 

int main()
{
  tMyVar* ptrMyVar = &myVar; 
  
  myVar++; 
  
  std::cout << "myVar = " << myVar << std::endl; 
  std::cout << "ptrMyVar = " << ptrMyVar << std::endl; 
  
  return 0;
}
```

Результат представлен на рисунке ниже: 

Не меняя переменной, явно преобразуем адрес переменной к типу указатель на `short`, 
используя `reinterpret_cast`, и присвоим локальной переменной типа `short*`.

Для этого изменим код программы следующим образом:
```
#include <iostream>

using tMyVar = short unsigned int; 
tMyVar myVar = 32767; 

int main()
{
  short* ptrMyVar = reinterpret_cast<short*>(&myVar);
  
  myVar++; 
  
  std::cout << "myVar = " << myVar << std::endl; 
  std::cout << "ptrMyVar = " << ptrMyVar << std::endl; 
  
return 0;
}
```
Вывести в терминал значение указателя - пояснить что это за значение.

