== Задание 1

1. Создал проект C++ c main.cpp

2. Не понял, как подключить к проекту файл cstartup.cpp

3. Создал папки AbstractHardware/Registers/FiledValues, Common

4. Создал структуру проекта в соотвествии со структурой папок

5. Из файла iarproject.map узнал размер проекта и настроил STACK, HEAP. 

6. Скопировал проект преподавателя https://github.com/lamer0k/stm32Labs/tree/master/Lab1

7. Скопировал содержимое папки из папки AHardware/Registers и Common с проекта преподавателя в свой проект

8. Написал программу в main.cpp

```
#include "gpiocregisters.hpp" //for GPIOC
#include "rccregisters.hpp"   //for RCC

int main()
{
  RCC::AHB1ENR::GPIOCEN::Enable::Set() ;
  GPIOC::MODER::MODER5::Output::Set() ;
  GPIOC::ODR::ODR5::Enable::Set() ;
  GPIOC::ODR::ODR5::Disable::Set() ;
  return 0 ;
}
```

== Задание 2

1. Откомпилировать и отлинковать программу не получилось ввиду полученных ошибок компилятора: 

`Error[Pe276]: name followed by "::" must be a class or namespace name C:\Users\User\Desktop\projects\microprocessors\Lab1\main.cpp 33`
`Error while running C/C++ Compiler`

В языке С++ :: - это оператор разрешения области видимости, который позволяет статически 
перемещаться по областям, таким как пространства имен и классы, чтобы ссылаться на нужный 
идентификатор.

Исходя из этого, я полагаю, что ошибка связана с тем, что линкер не видит Enable и Disable 
как часть пространства имен ODR5. Это можно решить, если более детально рассмотреть окружение 
проекта: сокрее всего, нужный файл, в котором объявлялись Enable и Disable, не был подключен.

Ввиду полученной ошибки я не смог выполнить дальнейшие задания. 